name: flutter_works
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^2.2.0
  dartz: ^0.10.0-nullsafety.1
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter_bloc: ^7.0.1
  get_it: ^7.2.0
  hive: ^2.0.4
  internet_connection_checker: ^0.0.1+2
  intl: ^0.17.0
  path_provider: ^2.0.2
  rxdart: ^0.27.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.6
  bloc_test: ^8.1.0
  mocktail: ^0.1.4
  very_good_analysis: ^2.1.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/flags/